name: Mobile app base workflow

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Build android
        uses: ./.github/workflows/ci-build-android.yml